tf_publisher_0:
  parent              : world
  child               : odom
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0, 1]
  source_topic        : "None"
  source_queue_size   : 0
tf_publisher_1:
  parent              : world
  child               : map
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : "None"
  source_queue_size   : 0
tf_publisher_2:
  parent              : odom
  child               : camera_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : "None"
  source_queue_size   : 0

tf_publisher_3:
  parent              : camera_link_optical
  child               : camera_0001/camera_link_optical
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : "None"
  source_queue_size   : 0

tf_publisher_4:
  parent              : odom
  child               : gopigo_0001_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0001/pose
  source_queue_size   : 0
tf_publisher_5:
  parent              : odom
  child               : gopigo_0002_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0002/pose
  source_queue_size   : 0
tf_publisher_6:
  parent              : odom
  child               : gopigo_0003_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0003/pose
  source_queue_size   : 0
tf_publisher_7:
  parent              : odom
  child               : gopigo_0003_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0003/pose
  source_queue_size   : 0
tf_publisher_8:
  parent              : odom
  child               : gopigo_0004_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0004/pose
  source_queue_size   : 0
tf_publisher_9:
  parent              : odom
  child               : gopigo_0005_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0005/pose
  source_queue_size   : 0
tf_publisher_10:
  parent              : odom
  child               : gopigo_0006_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0006/pose
  source_queue_size   : 0
tf_publisher_11:
  parent              : odom
  child               : gopigo_0007_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0007/pose
  source_queue_size   : 0
tf_publisher_12:
  parent              : odom
  child               : gopigo_0008_base
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : /gopigo_0008/pose
  source_queue_size   : 0

tf_publisher_13:
  parent              : camera_link_optical
  child               : camera_link_rgb_optical_frame
  position            : [0 ,0 ,0]
  orientation         : [0 ,0 ,0 ,1]
  source_topic        : None
  source_queue_size   : 1
