multi_boards:
  multi_board_id : [0, 1, 2]
  multi_board_0:
    marker_size : 0.1
    board_id : [0]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_1:
    marker_size : 0.1
    board_id : [1]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_2:
    marker_size : 0.1
    board_id : [2]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
