multi_boards:
  multi_board_id : [0, 1, 2,3,4,5,6,7]
  multi_board_0:
    marker_size : 0.092
    board_id : [0]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_1:
    marker_size : 0.092
    board_id : [1]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_2:
    marker_size : 0.092
    board_id : [2]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_3:
    marker_size : 0.092
    board_id : [3]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_4:
    marker_size : 0.092
    board_id : [4]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_5:
    marker_size : 0.092
    board_id : [5]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_6:
    marker_size : 0.092
    board_id : [6]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]
  multi_board_7:
    marker_size : 0.092
    board_id : [7]
    board_x  : [ 0.0 ]
    board_z  : [ 0.0 ]
    color_r  : [1.0 ]
    color_g  : [0.0]
    color_b  : [0.0 ]

#threshold_min: [0,0,100]
#threshold_max: [10,10,255]
threshold_min: [0,0,0]
threshold_max: [25,140,255]
image_to_real_mapping: [550,550]
